### PR TITLE
fix accountmetrics tools

### LINKED ISSUE #8: top-bandwidth-consumers tool returns no data when invoked with consumerType=user
When asking a question like: What amount of traffic did John Smith create yesterday?
the llm decides to invoke top-bandwidth-consumers and metrics_timeseries_query tools.
The tools returns no data, however in CMA it is possible to see traffic for that user for the same time-frame.

### PR DESCRIPTION
**Pull request by DanielPienicaCato**
Resolves #8

### CODE REVIEW

File: src/tools/users_metrics/UserMetricsTool.ts [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+        throw new Error("UserIDs are required for metrics analysis. Please use entity_lookup tool first:\n1. Call entity_lookup with type='vpnUser' to find user IDs\n2. Then call this tool with the discovered userIDs");
+    }
+    
+    variables.groupInterfaces = true;
+    variables.groupDevices = true;
+    return standardizeMetricsInput(variables);
+}
+
+const gqlQuery = `
+query metricsUser($accountID: ID!, $timeFrame: TimeFrame!, $userIDs: [ID!], $groupInterfaces: Boolean = true, $groupDevices: Boolean = true) {
```
Comment (eitan-cato) [inline src/tools/users_metrics/UserMetricsTool.ts:74]: please rename metricsUser -> userMetrics

**Review by eitan-cato — APPROVED** [review]
